# Generated by Django 4.0.2 on 2022-03-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_rename_product_description_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
